In [17]:
import pandas as pd
import plotly.io as pio
import plotly.express as px
import plotly
from plotly.subplots import make_subplots
import plotly.graph_objects as go
import plotly.io as pio
pio.renderers.default = 'iframe_connected'

In [18]:
df = pd.read_csv('Data/owid-covid-data.csv')
df.head()

,iso_code,continent,location,date,total_cases,new_cases,new_cases_smoothed,total_deaths,new_deaths,new_deaths_smoothed,...,gdp_per_capita,extreme_poverty,cardiovasc_death_rate,diabetes_prevalence,female_smokers,male_smokers,handwashing_facilities,hospital_beds_per_thousand,life_expectancy,human_development_index
0,AFG,Asia,Afghanistan,2020-02-24,1.0,1.0,NaN,NaN,NaN,NaN,...,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511
1,AFG,Asia,Afghanistan,2020-02-25,1.0,0.0,NaN,NaN,NaN,NaN,...,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511
2,AFG,Asia,Afghanistan,2020-02-26,1.0,0.0,NaN,NaN,NaN,NaN,...,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511
3,AFG,Asia,Afghanistan,2020-02-27,1.0,0.0,NaN,NaN,NaN,NaN,...,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511
4,AFG,Asia,Afghanistan,2020-02-28,1.0,0.0,NaN,NaN,NaN,NaN,...,1803.987,NaN,597.029,9.59,NaN,NaN,37.746,0.5,64.83,0.511

In [19]:
df.columns

Index(['iso_code', 'continent', 'location', 'date', 'total_cases', 'new_cases',
       'new_cases_smoothed', 'total_deaths', 'new_deaths',
       'new_deaths_smoothed', 'total_cases_per_million',
       'new_cases_per_million', 'new_cases_smoothed_per_million',
       'total_deaths_per_million', 'new_deaths_per_million',
       'new_deaths_smoothed_per_million', 'reproduction_rate', 'icu_patients',
       'icu_patients_per_million', 'hosp_patients',
       'hosp_patients_per_million', 'weekly_icu_admissions',
       'weekly_icu_admissions_per_million', 'weekly_hosp_admissions',
       'weekly_hosp_admissions_per_million', 'new_tests', 'total_tests',
       'total_tests_per_thousand', 'new_tests_per_thousand',
       'new_tests_smoothed', 'new_tests_smoothed_per_thousand',
       'positive_rate', 'tests_per_case', 'tests_units', 'total_vaccinations',
       'people_vaccinated', 'people_fully_vaccinated', 'new_vaccinations',
       'new_vaccinations_smoothed', 'total_vaccinations_per_hundred',
       'people_vaccinated_per_hundred', 'people_fully_vaccinated_per_hundred',
       'new_vaccinations_smoothed_per_million', 'stringency_index',
       'population', 'population_density', 'median_age', 'aged_65_older',
       'aged_70_older', 'gdp_per_capita', 'extreme_poverty',
       'cardiovasc_death_rate', 'diabetes_prevalence', 'female_smokers',
       'male_smokers', 'handwashing_facilities', 'hospital_beds_per_thousand',
       'life_expectancy', 'human_development_index'],
      dtype='object')

In [56]:
cases_vaccinations = df[['date', 'location', 'new_cases', 'total_vaccinations']]
cases_vaccinations = cases_vaccinations[cases_vaccinations['date'] > '2020-11-1']

In [57]:
USA = cases_vaccinations[cases_vaccinations['location'] == 'United States']
Israel = cases_vaccinations[cases_vaccinations['location'] == 'Israel']

In [58]:
USA.head()

             date       location  new_cases  total_vaccinations
84738  2020-11-10  United States   140496.0                 NaN
84739  2020-11-11  United States   146626.0                 NaN
84740  2020-11-12  United States   164839.0                 NaN
84741  2020-11-13  United States   180389.0                 NaN
84742  2020-11-14  United States   167761.0                 NaN

In [59]:
compare_fig = make_subplots(rows=1, cols=2, subplot_titles=("United States", "Israel"), specs=[[{"secondary_y": True},{"secondary_y": True}]])

compare_fig.add_trace(
    go.Scatter(x=USA['date'].tolist(), y=USA['new_cases'].tolist(), name='new Cases'),
    secondary_y=True, row=1, col=1
)

compare_fig.add_trace(
    go.Bar(x=USA['date'].tolist(), y=USA['total_vaccinations'].tolist(), name='Vaccinations'),
    secondary_y=False, row=1, col=1
)

compare_fig.add_trace(
    go.Scatter(x=Israel['date'].tolist(), y=Israel['new_cases'].tolist(), name='new Cases'),
    secondary_y=True, row=1, col=2
)

compare_fig.add_trace(
    go.Bar(x=Israel['date'].tolist(), y=Israel['total_vaccinations'].tolist(), name='Vaccinations'),
    secondary_y=False, row=1, col=2
)

compare_fig.update_layout(height=600, width=2000, title_text="Relationship of COVID-19 cases and Vaccinations")
compare_fig.update_yaxes(showgrid=False)
compare_fig.show()